- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop: "{{ (required_dirs | default([])) + [project_src] }}"

- name: Create required files
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ item.name }}"
    mode: "0644"
  loop: "{{ required_files }}"
  when: required_files is defined

- name: Write Docker Compose file
  ansible.builtin.copy:
    content: "{{ docker_conf | to_nice_yaml }}"
    dest: "{{ project_src }}/docker-compose.yml"
    mode: "0644"

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ project_src }}"

- name: Configure Nginx site
  ansible.builtin.import_role:
    name: geerlingguy.nginx
  become: true
  when: nginx_conf is defined and nginx_conf | bool
  vars:
    nginx_vhosts:
      - server_name: "{{ nginx_conf.server_name }}"
        state: "present"
        listen: "{{ nginx_conf.listen }}"
        extra_parameters: |
          location / {
            proxy_pass       http://localhost:{{ nginx_conf.app_port }};
            proxy_buffering  off;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
          }
