---
collections:
  - name: ansible.utils
  - name: community.proxmox
  - name: prometheus.prometheus
  - name: grafana.grafana
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
  - name: community.docker
  - name: community.postgresql

roles:
  - name: geerlingguy.docker
  - name: geerlingguy.pip
  - name: geerlingguy.nginx
