required_dirs: []
  # - /home/user/app
  # - /home/user/app/config
  # - /home/user/app/data
required_files: []
  # - name: /home/user/app/.env
  #   content: |
  #     COMPOSE_PROJECT_NAME=radicale
  #     UID=$(id -u)
  #     GID=$(id -g)
